services:
  app:
    ports:
      - "8080:8080"
    build: .
    environment:
      - DB_CONNECTION_STRING=DB_CONNECTION_STRING=root:root@tcp(db)/queensscorecard
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root