// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Score struct {
	ID             int32
	Name           string
	Gamenumber     int32
	Secondstosolve int32
	Timestamp      int32
}
