name: Trigger auto deployment for queensscorecard

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/queensscorecard-AutoDeployTrigger-4e90afa4-2f41-4b66-a291-73a0790bfb16.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.QUEENSSCORECARD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QUEENSSCORECARD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QUEENSSCORECARD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: heyner128.azurecr.io
          registryUsername: ${{ secrets.QUEENSSCORECARD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUEENSSCORECARD_REGISTRY_PASSWORD }}
          containerAppName: queensscorecard
          resourceGroup: DefaultResourceGroup-PAR
          imageToBuild: heyner128.azurecr.io/queensscorecard:${{ github.sha }}


